### ISSUE TITLE
Demo page is broken

### ISSUE THREAD

**Issue by av01d** [FacilMap/Leaflet.DraggableLines#3]
The demo page at https://unpkg.com/leaflet-draggable-lines@1.1.0/example.html is broken, it just shows an empty page.
JS console shows this:
`Uncaught TypeError: Failed to resolve module specifier "leaflet". Relative references must start with either "/", "./", or "../".`

**Comment by av01d** [comment]
Don't forget to publish your fix on unpk.com, the demo page currently still doesn't work.
But thanks for the fix!

**Comment by cdauth** [comment]
The latest version works for me: https://unpkg.com/leaflet-draggable-lines/example.html
Does it not work for you?

**Comment by av01d** [comment]
No, it doesn't. Reason: my default browser is Firefox. It does work in Chrome.
Console error in Firefox: Uncaught TypeError: Error resolving module specifier “leaflet”. Relative module specifiers must start with “./”, “../” or “/”.
(Example.html, line 29)

**Comment by cdauth** [comment]
The demo page should work starting with Firefox 108, which it seems was released today. I have just upgraded Firefox and it seems to work for me now.

This was a compromise that I had to make in order to get the demo page working both under the Vite dev server and directly in the browser. I believe it is acceptable because it is only a demo page, and new Firefox version will spread in the next weeks.

**Comment by av01d** [comment]
I just upgraded Firefox to version 108 (on MacOS), and unfortunately the demo page still doesn't show anything.
The console reports: `Uncaught TypeError: The specifier “leaflet” was a bare specifier, but was not remapped to anything. Relative module specifiers must start with “./”, “../” or “/”.`
